Organisms plans
shinonome-inc/hiroya-frontend-basic-last-assignment pull request #11
Opened 2022-11-10 10:05 UTC by hiroyashiratori

## セルフチェック
- [o] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [o] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [o] 記述の重複はないか

リンク
https://62e4eb9ab0d43e4794767f73-fwuwmyduji.chromatic.com/?path=/story/organisms-plans--plans

2022-11-11 11:44 UTC, caramelribon reviewed
コメントしました！

2022-11-11 11:44 UTC, caramelribon commented on src/components/organisms/plans/plans.html
> +<div class="plans">
間違っているわけではないんですが、個人的にこうした方がよりいいかなって思ったことです！
ページを完成させるときに、organismsで作ったものを並べていくんですが、そのときにそれぞれのかたまりをsectionタグで囲んでいくと、あとで並べたときに、divタグばっかなのが、sectionタグによってかたまりが見やすくなるのかなって思います！この場合`<section class="plans">`にするって感じです！

2022-11-11 11:44 UTC, caramelribon commented on src/components/organisms/plans/plans.html
> +  <div class="plans-button">
`<a class="button">プラン料金</a>`だけで大丈夫です！
`.button{}`の中で、スタイルを追加することによって、atoms-buttonで作った`.button{}`のスタイルの中に追加されます！

2022-11-11 11:44 UTC, caramelribon commented on src/components/organisms/plans/plans.scss
> +  .plans-button {
ここが`.button{}`でスタイル変更してみてください！

2022-11-11 11:44 UTC, caramelribon commented on src/components/organisms/plans/plans.scss
> +    margin: 35px auto 100px;
ここのボタンの上のmargin-topはいらないです！
`<ul class="plan">`でmargin-bottomを設定しているので大丈夫です！
またボタンでmargin-bottomを設定していますが、これはFigmaをみるとボタンのmargin-bottomではなく、このプランのリスト全体に対するmargin-bottomなので、ここではなく、一番の大枠に設定しましょう！

2022-11-11 11:44 UTC, caramelribon commented on src/components/organisms/plans/plans.html
> +  <div class="row row-cols-1 row-cols-md-3 plans">
ここで`.plans`を加えていると思うんですが、一番外側で`plans`を設定しているので、違う名前にした方がいいと思います！

2022-11-11 11:44 UTC, caramelribon commented on src/components/organisms/plans/plans.scss
> +  .col:nth-child(2) .plan {
この部分はmolecules-planでスタイルを決めているはずなので、ここではスタイルを入れる必要がないと思います！
もしmolecules-planでのスタイルが反映されなくて困っていたら教えて下さい！

2022-11-12 08:41 UTC, hiroyashiratori commented on src/components/organisms/plans/plans.scss
> +  .col:nth-child(2) .plan {
修正しました！

2022-11-12 08:45 UTC, hiroyashiratori commented on src/components/organisms/plans/plans.scss
> +  .col:nth-child(2) .plan {
> この部分はmolecules-planでスタイルを決めているはずなので、ここではスタイルを入れる必要がないと思います！ もしmolecules-planでのスタイルが反映されなくて困っていたら教えて下さい！

colセレクタで囲っているのでこれがないとお手本どうりに作れません。ほかのやり方を探ってみましたができなかったです。正しいヒントをいただきたいです。

2022-11-13 10:21 UTC, hiroyashiratori commented on src/components/organisms/plans/plans.scss
> +  .col:nth-child(2) .plan {
> この部分はmolecules-planでスタイルを決めているはずなので、ここではスタイルを入れる必要がないと思います！ もしmolecules-planでのスタイルが反映されなくて困っていたら教えて下さい！

colで囲っているのでこれがないと反映されないんですが…

2022-11-13 13:48 UTC, caramelribon reviewed
コメントしました！！

2022-11-13 13:48 UTC, caramelribon commented on src/components/organisms/plans/plans.scss
> +  .col:nth-child(2) .plan {
なるほどです！解決策を3つほど上げるので、どれか当てはまるもので実装してみてください！
それでも無理そうでしたら、また質問してください！！
1. `<div class="col">`で囲わなくてもgrid構造になるかなって思いました！
2. 書き方を以下のようにする！[bootstrpのgridシステム](https://getbootstrap.jp/docs/4.2/layout/grid/)
   (Stacked to horizontalやMix and matchを読むとわかりやすいかなと思います！)
```
<div class="row">
  <ul class="md以上で3つを横並べにするbootstrapのスタイルを加える"></ul>
  <ul class="md以上で3つを横並べにするbootstrapのスタイルを加える"></ul>
  <ul class="md以上で3つを横並べにするbootstrapのスタイルを加える"></ul>
</div>
```
3. それでも無理そうでしたら、CSSの方でスタイルを設定する

2022-11-13 13:48 UTC, caramelribon commented on src/components/organisms/plans/plans.scss
> +      margin: 24px auto 35px;
ここのmargin-topは.planの方で設定してあるので、いらないと思います！

2022-11-27 11:45 UTC, hiroyashiratori commented
アドバイスありがとうございます！

<div class="row">
  <ul class="md以上で3つを横並べにするbootstrapのスタイルを加える"></ul>
  <ul class="md以上で3つを横並べにするbootstrapのスタイルを加える"></ul>
  <ul class="md以上で3つを横並べにするbootstrapのスタイルを加える"></ul>
</div>

これをつかってうまくいったのですが、planカードにCSSのほうでmarginやgapで間隔をつけようとしたところ３つ目のカードが折り返してしまうという問題が起きました。どうすればいいでしょうか、、paddingは二つ目のplanカードのborderのせいでスタイルが崩れてしまいます。

2022-11-30 14:45 UTC, SakaueYae commented
![image](https://user-images.githubusercontent.com/101164626/204824336-f46a71e2-ad6f-42c2-a853-416319c75162.png)
`.col-md-4`自体にpaddingがもともとついており、それをplan同士の間の余白とするのが良いと思います！
今はmolecules-planで`.plan`に`padding: 0;`がついているため、`.col-md-4`のpaddingが消されている状態です。

![image](https://user-images.githubusercontent.com/101164626/204825093-9cb8733c-9964-4661-ac25-70bb19f72b25.png)
ここの記述を消すだけだと見た目が崩れてしまうため、`.plan`の1つ外側をdivタグなどで囲みそれに`.col-md-4`をつけてあげることで、paddingで両脇の余白を再現することができると思います！（画像は1つ目のplanのみを修正したものです。）

2022-12-01 07:03 UTC, hiroyashiratori commented
ありがとうございます！せっかくアドバイスいただいたのに申し訳ないのですが、二つ目のカードにborder色変化のスタイルが適用されないので新しく思いついた違う方法を試しました。gapとflex-wrapを組み合わせたこのやり方でも問題ないでしょうか？

それと全体の余白の取り方が良く分かりませんでした。とりあえずfigmaと同じようにしましたが合っていますでしょうか？

2022-12-02 01:14 UTC, MinamiHotta commented
> ありがとうございます！せっかくアドバイスいただいたのに申し訳ないのですが、二つ目のカードにborder色変化のスタイルが適用されないので新しく思いついた違う方法を試しました。gapとflex-wrapを組み合わせたこのやり方でも問題ないでしょうか？

見た目が正しければ問題ないです！

> それと全体の余白の取り方が良く分かりませんでした。とりあえずfigmaと同じようにしましたが合っていますでしょうか？

こちら参考にしてください↓
https://playground.wraptas.site/df6859770f3c4c248688d88eadad03cf

2022-12-02 01:14 UTC, MinamiHotta commented on src/components/organisms/plans/plans.scss
> +    padding: 0 114px;
![image](https://user-images.githubusercontent.com/104500220/205186970-4aa9a576-321c-4782-928f-21070f601c3e.png)
![image](https://user-images.githubusercontent.com/104500220/205186992-09380277-c03f-473c-a86b-aaa7f7d88143.png)
Figmaをよく見てbutton下の余白を設定してください

2022-12-02 09:20 UTC, hiroyashiratori commented
リンクありがとうございます。figmaのお手本の余白はcontainerがついている前提で決められるからcontainerを付けた上で余白を設定するということですか？
そのようにしたのですがなぜかお手本どうりの余白にならないです。。

2022-12-02 13:40 UTC, MinamiHotta commented
> リンクありがとうございます。figmaのお手本の余白はcontainerがついている前提で決められるからcontainerを付けた上で余白を設定するということですか？ そのようにしたのですがなぜかお手本どうりの余白にならないです。。

横幅に限って言えば、containerを付けていればご自身で余白を設定しなくてもFigma通りの見た目になると思うのですがいかがでしょう

2022-12-02 13:40 UTC, MinamiHotta commented on src/components/organisms/plans/plans.scss
> +    margin: 0 114px 35px 114px;
今あるここらへんのmarginをすべて消したらうまくいくと思うのですがいかがでしょう？
一旦検証ツールで試してから、もし不具合あれば教えてください

2022-12-03 13:49 UTC, MinamiHotta commented
![image](https://user-images.githubusercontent.com/104500220/205444059-792346a7-225b-4bd7-bde9-df587e284121.png)
すみません、1点だけ！お手本に忠実になるため、<br>使って改行も再現してほしいです！

2022-12-03 13:51 UTC, MinamiHotta commented
すみません1点だけ！お手本通りに<br>使うなどして改行お願いします💦

![image](https://user-images.githubusercontent.com/104500220/205444175-aff66fb5-1b0e-446b-ae7d-f761791d348b.png)
![image](https://user-images.githubusercontent.com/104500220/205444178-08c2ef97-6c20-4e9c-abd1-8eefeb9e3b7f.png)

2022-12-03 14:05 UTC, higashiji2000 commented on src/components/organisms/plans/plans.scss
> +}
```suggestion
.plans {
  .row {
    gap: 15px;
    flex-wrap: nowrap;
    justify-content: center;
    @media screen and (max-width: $breakpoint-md) {
      flex-direction: column;
    }
  }
  .button {
    display: flex;
    justify-content: center;
    margin-top: 40px;
    @media screen and (max-width: $breakpoint-md) {
      margin-top: 0;
    }
  }
}
```
この書き方だと、他のコンポーネントでrowを使っていた場合、そちらにも適用されてしまいます。
予想外の副作用を防ぐため、基本的にhtmlの構造をscssにも反映させて、影響範囲を狭くすることを心がけるのがおすすめです。

2022-12-04 08:14 UTC, hiroyashiratori commented
![image](https://user-images.githubusercontent.com/105481118/205480809-3e3a9e56-bb85-47c7-878d-b6f83f63a73b.png)
![image](https://user-images.githubusercontent.com/105481118/205480823-a6a629c2-37f9-4baf-b719-2dbae351de27.png)

2022-12-04 08:33 UTC, hiroyashiratori commented
![image](https://user-images.githubusercontent.com/105481118/205480918-b3587d53-c56a-4521-8f59-9541fe053dcc.png)
![image](https://user-images.githubusercontent.com/105481118/205481381-927b59a8-5ccc-4aff-babd-96de834b830a.png)

2022-12-04 08:51 UTC, hiroyashiratori commented
messageのテキストボックスがお手本どうりに改行できなかった (一番最初の画像) ので、原因を探ってみました。

検証ツールで boxsizing: border-box; のチェックを外すとお手本どうりになるのが分かったので、sectionタグplansに boxsizing: content-box; をつけてみました。

改行の問題は解決しましたが余白が、画面幅がある程度大きい(breakpoint-m以上？)時border-boxだった時よりも狭くなっています。

2022-12-04 09:05 UTC, hiroyashiratori commented
「平日～」の行の幅がborder-boxの有り無しで変わっている気がします…

2022-12-05 04:23 UTC, higashiji2000 requested changes
改行の位置に関しては、お手本と完全に同じにする必要はありません。
今回でいえば、「プランなど、」の直後や「いただけます。」の直後など、明らかに意図的に改行しているのがわかる部分には `<br>` タグを入れることができていれば基本的に問題はありません。
案件等でも改行位置等の細かいスタイルの違いの優先度は低く、同じ労力でサイト全体のクオリティ向上や納期短縮にインパクトの大きい仕事をしたほうが歓迎されます。
<img width="410" alt="image" src="https://user-images.githubusercontent.com/83479175/205548496-710f3047-64bf-4f11-b79a-56ea1e39ae93.png">

---
いろいろ書いてしまいましたが、下記を修正できたら再度PRを提出してください。

- box-sizingはborder-boxのままにする
- bootstrapのgridシステムを使わないようにする

2022-12-05 04:23 UTC, higashiji2000 commented on src/components/organisms/plans/plans.scss
> +  box-sizing: content-box;
box-sizingは、widthおよびheightが指定されている際に、その数値にborderやpaddingを含めるかどうかを指定するプロパティです。
cssスタイリングの枠組みを規定するものなので、基本的にサイト全体に対して同じものを指定するべきです。
参考：https://zero-plus.io/media/box-sizing/


今回は、containerにmax-widthがついているので、box-sizingの値によってpaddingを含めるかどうかが変わり、結果的に幅が変わっています。
画像右下にボックスモデルと幅が表示されているので参考にしてみてください。
![image](https://user-images.githubusercontent.com/83479175/205546871-a07d3d29-02e8-4c03-b4cb-dfc3d3d40b7e.png)
content-box
content（青）の部分が720pxになっている

![image](https://user-images.githubusercontent.com/83479175/205546908-4803ea9c-d73c-4aa3-9d46-4a3d2e0c6a5e.png)
border-box
content + padding の合計が 720px になっている

2022-12-05 04:23 UTC, higashiji2000 commented on src/components/organisms/plans/plans.html
> +    <div class="row">
![image](https://user-images.githubusercontent.com/83479175/205547652-5dc6d847-5ded-49df-924b-24d49a35bd09.png)
bootstrapの `row` は、 `container` の直下に配置することが前提となっていることなどが理由で、要素がコンテナからはみ出てしまっています。
確認したところ `col` のあたりなども bootstrap とかなり干渉してしまっているようなので、bootstrapを使わずに css の flexbox や grid を使って実装してみてほしいです。

2022-12-06 06:57 UTC, MoAI522 approved these changes
LGTM

2022-12-06 06:57 UTC, merged